import { Tag, Tooltip } from "@/ui-kit/eat";
import type { ProviderUsed, SynthesisSource } from "../types";

interface SourcePillProps {
	source: SynthesisSource;
	provider: ProviderUsed;
}

// providerLabel renders a human-friendly label for the tooltip copy so
// the user sees "Claude (user config)" or "System default" instead of
// raw enum values.
function providerLabel(provider: ProviderUsed): string {
	switch (provider) {
		case "user":
			return "你配置的 Provider";
		case "system_default":
			return "Richman 系统默认 Provider";
		case "none":
			return "未使用 LLM";
		default:
			return "未知";
	}
}

// SourcePill renders a small provenance tag on each decision card that
// tells the user whether the copy was generated by an LLM, by the rules
// engine, or by a mixed pipeline. When the source is "unknown" — which
// covers historical rows written before migration 007 — the pill is
// hidden entirely so the user is not burdened with a sentinel value.
export function SourcePill({ source, provider }: SourcePillProps) {
	if (source === "unknown") return null;

	if (source === "llm") {
		return (
			<Tooltip title={`由 AI 解读生成（${providerLabel(provider)}）`}>
				<Tag color="processing" data-testid="source-pill-llm">
					AI
				</Tag>
			</Tooltip>
		);
	}

	if (source === "mixed") {
		return (
			<Tooltip title={`文案由 AI 解读生成，建议动作由规则引擎兜底（${providerLabel(provider)}）`}>
				<Tag color="default" data-testid="source-pill-mixed">
					Mixed
				</Tag>
			</Tooltip>
		);
	}

	// template branch
	return (
		<Tooltip title="由规则引擎生成 · 配置 LLM Provider 可启用 AI 解读">
			<Tag color="default" data-testid="source-pill-template">
				Rules
			</Tag>
		</Tooltip>
	);
}
