import { Tag, Tooltip } from "@/ui-kit/eat";
import { useTranslation } from "react-i18next";
import type { ProviderUsed, SynthesisSource } from "../types";

interface SourcePillProps {
	source: SynthesisSource;
	provider: ProviderUsed;
}

// SourcePill renders a small provenance tag on each decision card that
// tells the user whether the copy was generated by an LLM, by the rules
// engine, or by a mixed pipeline. When the source is "unknown" — which
// covers historical rows written before migration 007 — the pill is
// hidden entirely so the user is not burdened with a sentinel value.
export function SourcePill({ source, provider }: SourcePillProps) {
	const { t } = useTranslation("app");

	// providerLabel maps the ProviderUsed enum to a human-readable string
	// using i18n so the label updates when the user switches language.
	const providerLabel = (p: ProviderUsed): string => {
		switch (p) {
			case "user":
				return t("decisionCard.provider.user");
			case "system_default":
				return t("decisionCard.provider.system_default");
			case "none":
				return t("decisionCard.provider.none");
			default:
				return t("decisionCard.provider.unknown");
		}
	};

	if (source === "unknown") return null;

	if (source === "llm") {
		return (
			<Tooltip title={t("decisionCard.source.llmTooltip", { provider: providerLabel(provider) })}>
				<Tag color="processing" data-testid="source-pill-llm">
					{t("decisionCard.source.llm")}
				</Tag>
			</Tooltip>
		);
	}

	if (source === "mixed") {
		return (
<<<<<<< HEAD
			<Tooltip title={t("decisionCard.source.mixedTooltip", { provider: providerLabel(provider) })}>
				<Tag color="blue" data-testid="source-pill-mixed" style={{ background: "transparent" }}>
					{t("decisionCard.source.mixed")}
				</Tag>
			</Tooltip>
		);
	}

	// template branch
	return (
		<Tooltip title={t("decisionCard.source.templateTooltip")}>
			<Tag color="default" data-testid="source-pill-template">
				{t("decisionCard.source.template")}
			</Tag>
		</Tooltip>
	);
}
