run:
  timeout: 5m

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - gocritic
    - gofmt
    - goimports
    - misspell
    - revive

linters-settings:
  revive:
    rules:
      - name: line-length-limit
        arguments:
          - 120
  misspell:
    locale: US
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
