version: "2"

run:
  timeout: 5m

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - gocritic
    - misspell
    - revive
  settings:
    revive:
      rules:
        - name: line-length-limit
          arguments:
            - 120
    misspell:
      locale: US
    gocritic:
      enabled-tags:
        - diagnostic
        - style
        - performance

formatters:
  enable:
    - gofmt
    - goimports
