// Barrel export for Ant Design components.
// All application code should import from this module instead of directly from antd packages.

export {
	App,
	Avatar,
	Breadcrumb,
	Button,
	Card,
	Checkbox,
	Col,
	Collapse,
	ConfigProvider,
	DatePicker,
	Divider,
	Drawer,
	Dropdown,
	Empty,
	Form,
	Input,
	InputNumber,
	List,
	Menu,
	message,
	Modal,
	notification,
	Popconfirm,
	Progress,
	Radio,
	Row,
	Select,
	Skeleton,
	Space,
	Spin,
	Statistic,
	Steps,
	Switch,
	Table,
	Tabs,
	Timeline,
	Tooltip,
	Typography,
	Upload,
	Badge,
	Alert,
	Result,
	Segmented,
	Flex,
	Image,
	theme,
} from "antd";

export { Tag } from "./Tag";

export type { UploadProps, UploadFile } from "antd";

export type { ThemeConfig, FormInstance } from "antd";

export {
	ProLayout,
	ProTable,
	ProForm,
	ProFormText,
	ProFormSelect,
	ProFormDigit,
	ProDescriptions,
	StatisticCard,
	PageContainer,
	ProCard,
} from "@ant-design/pro-components";

export {
	DashboardOutlined,
	UserOutlined,
	SettingOutlined,
	BellOutlined,
	PieChartOutlined,
	FundOutlined,
	LogoutOutlined,
	PlusOutlined,
	EditOutlined,
	DeleteOutlined,
	SearchOutlined,
	ReloadOutlined,
	CheckOutlined,
	CloseOutlined,
	ExclamationCircleOutlined,
	InfoCircleOutlined,
	MenuFoldOutlined,
	MenuUnfoldOutlined,
	SunOutlined,
	MoonOutlined,
	GlobalOutlined,
	LineChartOutlined,
	BarChartOutlined,
	StockOutlined,
	QuestionCircleOutlined,
	CameraOutlined,
	LeftOutlined,
	InboxOutlined,
	UploadOutlined,
	RobotOutlined,
} from "@ant-design/icons";
