// Decision card TypeScript types.
//
// These types mirror the backend DTO defined in
// backend/internal/api/v1/decision_card.go (DecisionCardDTO) and the shared
// recommendation structures in backend/internal/analysis/recommendation.
// They are intentionally a direct structural copy so the UI can consume the
// JSON payload as-is without a runtime mapper. Keep the field order / names
// in sync with the Go source when changing either side.

// TriggerType is the discriminator for a step's trigger condition.
export type TriggerType = "price" | "time" | "event";

// ExecutionType describes the shape of an execution plan.
export type ExecutionType = "one-shot" | "staged" | "monitor";

// Action enumerates the five base recommendation actions. String values are
// the canonical wire format used in JSON payloads.
export type Action =
	| "aggressive_add"
	| "small_add"
	| "hold"
	| "gradual_reduce"
	| "control_position";

// BadgeState is the 8-state badge enum from PRD §3.4. "none" means no badge
// should be displayed.
export type BadgeState =
	| "none"
	| "data_degraded"
	| "first_analysis"
	| "action_upgrade"
	| "action_downgrade"
	| "signal_flip"
	| "plan_adjust"
	| "confidence_shift";

// SynthesisSource records whether the card text came from an LLM, a
// deterministic rules engine fallback, or a mix of the two. Backend nullable
// values are mapped to "unknown" at the API boundary so the UI can branch on
// a closed union.
export type SynthesisSource = "llm" | "template" | "mixed" | "unknown";

// ProviderUsed records which layer of the fallback chain actually produced
// the card. "user" means the user-configured provider answered, "system_default"
// means Richman's shared provider answered, "none" means neither LLM layer
// answered (pure template), and "unknown" is the null-at-rest sentinel.
export type ProviderUsed = "user" | "system_default" | "none" | "unknown";

// TriggerPayload is the optional structured representation of a trigger
// condition. Only fields relevant to the TriggerType are populated.
export interface TriggerPayload {
	priceOp?: string;
	priceValue?: number;
	deadlineIso?: string;
	eventKey?: string;
}

// StructuredRationale holds the semantic explanation for a single execution
// step. Each field is a short sentence generated by the LLM. Empty strings
// indicate the field was not provided.
export interface StructuredRationale {
	triggerReason: string;
	positionReason: string;
	precondition: string;
	fallback: string;
	timeWindow: string;
}

// Type guard for backward compat with pre-v2 cards that stored rationale as
// a plain string. The backend custom UnmarshalJSON converts legacy strings
// into StructuredRationale, but the API response may still contain old-format
// cards during the migration window.
export function isStructuredRationale(r: unknown): r is StructuredRationale {
	return typeof r === "object" && r !== null && "triggerReason" in r;
}

// Step is a single ordered action inside an execution plan.
export interface Step {
	order: number;
	triggerType: TriggerType;
	triggerValue: string;
	triggerPayload?: TriggerPayload;
	deltaPct: number;
	lotCount?: number;
	rationale: StructuredRationale | string;
	// rationaleTemplate is set by the rules-engine fallback path. When present,
	// rationale fields are empty and the frontend resolves localized text from
	// decisionCard.executionPlan.fallbackRationale.<template>.<field> i18n keys.
	// Known values: "monitor" | "aggressiveAdd" | "smallAdd" | "gradualReduce" | "control".
	rationaleTemplate?: string;
}

// Execution is a complete execution plan attached to a Recommendation.
export interface Execution {
	type: ExecutionType;
	steps?: Step[];
	stopLoss?: number | null;
	takeProfit?: number | null;
	validDays: number;
}

// Recommendation is the full structured recommendation surfaced on a card.
// v1 decision cards (pre-migration 022) are persisted with recommendation_json
// either NULL or a zero-valued object — at the wire level their `action` field
// collapses to an empty string, so callers must treat the union as possibly
// empty when rendering legacy rows. See isV2Card below for the version probe.
export interface Recommendation {
	action: Action | "";
	actionLevel: number;
	label: string;
	currentPositionPct: number;
	targetPositionPct: number;
	execution: Execution;
}

// isV2Card returns true when the decision card carries a populated
// recommendation.action — i.e. it was produced by the v2 analysis pipeline
// (migration 022 onwards). v1 rows pre-date structured recommendations and
// serialize `action` as an empty string because the backend zero-value of the
// Go `Action` type is "". Per frontend-v2-trd SS16.3, the two rendering
// paths live in a single component and branch on this probe.
export function isV2Card(card: Pick<DecisionCardDTO, "recommendation">): boolean {
	return Boolean(card.recommendation?.action);
}

// DecisionCardDTO mirrors backend v1.DecisionCardDTO.
export interface DecisionCardDTO {
	cardId: number;
	userId: number;
	holdingId: number;
	assetCode: string;
	assetName: string;
	assetType: string;
	costPrice: number;
	currentPrice: number;
	quantity: number;
	positionRatio: number;
	positionAmount?: number | null;
	trendDirection: string;
	trendSummary: string;
	positionDirection: string;
	positionSummary: string;
	catalystDirection: string;
	catalystSummary: string;
	confidence: number;
	actionAdvice: string;
	detailedAdvice: string;
	riskWarnings: string[];
	todayHighlights: string;
	weightTrend: number;
	weightPosition: number;
	weightCatalyst: number;
	analyzedAt: string;
	createdAt: string;

	// Structured recommendation + badge diff fields (migration 006).
	recommendation: Recommendation;
	actionLevel: number;
	targetPositionRatio: number;
	targetPositionAmount?: number | null;
	badgeState: BadgeState;
	confidenceDelta: number;
	prevCardId?: number | null;
	executionFingerprint: string;

	// Provenance fields added by the LLM degraded contract work. Backend may
	// emit null for historical rows that have not yet been reanalyzed; the
	// API client normalizes null to "unknown" so downstream components can
	// rely on the closed union.
	synthesisSource: SynthesisSource;
	providerUsed: ProviderUsed;
}

// RerunAnalysisResponse is the accepted response for POST /analysis/trigger.
export interface RerunAnalysisResponse {
	taskId: string;
	message?: string;
}

// ReanalyzeAllResponse is the accepted response for
// POST /analysis/reanalyze-all. It mirrors RerunAnalysisResponse shape on
// purpose so UI callers can reuse the same progress polling surface.
export interface ReanalyzeAllResponse {
	taskId: string;
	message?: string;
}

// Analysis task progress types — used by the progress drawer and polling hook.

export type TaskStepKey =
	| "fetch_data"
	| "calc_indicators"
	| "recommendation"
	| "llm_synthesis"
	| "persist";

export type TaskStepStatus = "pending" | "running" | "done" | "failed";

export interface AnalysisTaskStep {
	key: TaskStepKey;
	status: TaskStepStatus;
	durationMs: number | null;
}

export type HoldingAnalysisStatus = "pending" | "running" | "done" | "failed";

export interface HoldingProgress {
	symbol: string;
	name: string;
	status: HoldingAnalysisStatus;
	progress: number;
	synthesisSource: string | null;
	providerUsed: string | null;
	durationMs: number | null;
}

export interface AnalysisTaskLog {
	ts: string;
	level: "info" | "warn" | "error";
	msg: string;
}

export type AnalysisTaskStatus = "pending" | "running" | "completed" | "failed";

export interface AnalysisTask {
	taskId: string;
	userId: number;
	status: AnalysisTaskStatus;
	progress: number;
	error?: string;
	startedAt: string;
	doneAt?: string;
	currentHolding: string;
	holdings: HoldingProgress[];
	steps: AnalysisTaskStep[];
	logs: AnalysisTaskLog[];
}
